### ISSUE TITLE
Doesn't actually move to the selected pane when it's in the same session

### ISSUE THREAD

**Issue by ryuheechul** [laperlej/zellij-session-tree#3]
It appears to be there is a bug and the behavior that I discovered is like this: it can choose specific tab and specific pane as long as choosing a different session but nothing happens when choosing things within the same session.

tested versions:
- zellij 0.41.1
- zellij-choose-tree 0.4.1

**Comment by laperlej** [comment]
Thanks for bringing this up, I think the switch function provided by the zellij plugin api fails if the session is already active and the other params are just ignored. I'll look into this edge case and use other api calls when I have some time.
